In [1]:
import numpy as np

In [3]:
np.__version__

'1.14.0'

In [8]:
vetor1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [9]:
print(vetor1)

[1 2 3 4 5 6 7 8 9 0]


In [10]:
type(vetor1)

numpy.ndarray

In [11]:
vetor1.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 45], dtype=int32)

In [14]:
print(vetor1[0])

1


In [15]:
vetor1[0] = 100

In [16]:
print(vetor1)

[100   2   3   4   5   6   7   8   9   0]


In [17]:
print(vetor1.shape)

(10,)
