In [1]:
import numpy as np

In [11]:
vetor2 = np.arange(0.,4.5,.5)

In [12]:
print(vetor2)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4. ]


In [13]:
type(vetor2)

numpy.ndarray

In [14]:
vetorZeros = np.zeros(10)

In [15]:
print(vetorZeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [20]:
z = np.eye(3)

In [21]:
print(z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [22]:
d = np.diag(np.array([1,2,3,4]))

In [23]:
print(d)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [27]:
print(np.linspace(0, 10,15))

[ 0.          0.71428571  1.42857143  2.14285714  2.85714286  3.57142857
  4.28571429  5.          5.71428571  6.42857143  7.14285714  7.85714286
  8.57142857  9.28571429 10.        ]


In [28]:
print(np.logspace(0, 10,15))

[1.00000000e+00 5.17947468e+00 2.68269580e+01 1.38949549e+02
 7.19685673e+02 3.72759372e+03 1.93069773e+04 1.00000000e+05
 5.17947468e+05 2.68269580e+06 1.38949549e+07 7.19685673e+07
 3.72759372e+08 1.93069773e+09 1.00000000e+10]
