In [1]:
import numpy as np

In [2]:
#vetor = array unidimensional
#matriz = array bidimensional
#tensor = array tridimensional

In [3]:
matriz = np.array([[1,2,3],[4,5,6]])

In [4]:
print(matriz)

[[1 2 3]
 [4 5 6]]


In [5]:
print(matriz.shape)

(2, 3)


In [7]:
matriz1 = np.ones((2,3))

In [8]:
print(matriz1)

[[1. 1. 1.]
 [1. 1. 1.]]


In [9]:
type(matriz)

numpy.ndarray

In [10]:
type(matriz1)

numpy.ndarray

In [11]:
print(matriz.size)

6
