In [1]:
import numpy as np

In [2]:
vetor = np.arange(3)

In [4]:
a = np.diag(vetor)

In [5]:
print(a)

[[0 0 0]
 [0 1 0]
 [0 0 2]]


In [6]:
a[1,1]

1

In [7]:
a[-1]

array([0, 0, 2])

In [9]:
b = np.arange(10)

In [10]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
b[2:9:3]

array([2, 5, 8])

In [14]:
print(a.min())

0


In [15]:
print(a.max())

2


In [17]:
a = np.array([1,2,3]) + 1.5

In [18]:
a

array([2.5, 3.5, 4.5])

In [19]:
print(np.around(a))

[2. 4. 4.]


In [22]:
c = a.flatten()

In [23]:
c

array([2.5, 3.5, 4.5])

In [24]:
np.repeat(c, 3)

array([2.5, 2.5, 2.5, 3.5, 3.5, 3.5, 4.5, 4.5, 4.5])

In [27]:
np.tile(c, 2)

array([2.5, 3.5, 4.5, 2.5, 3.5, 4.5])